# Site
name: 'Green Analytics'
description: 'An interseting take on the changes in the environment around us.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'greenanalytica'
email: 'utkarshrai98@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    utkarsh:
      name:           Utkarsh
      site:           http://www.utkarshrai.in
      avatar:         assets/images/utkarsh_avatar.jpg
      bio:            "Hi, I am Utkarsh, the creator of Green Analytics. I hope you like it!"
      email:          utkarshrai98@gmail.com
      twitter:        https://twitter.com/utkarshrai98

    jane:
      name:           jane
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar2.jpg
      bio:            "She doesn't exist for now"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: utkarsh
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]