# Site
name: 'ज्ञानोदय बाल एवं महिला कल्याण समिति'
description: 'NGO, Mirzzapur'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'greenanalytica'
email: 'utkarshrai98@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    gbkms:
      name:           GBKMS
      site:           https://www.utkarshrai.in
      avatar:         assets/images/avatar.jpg
      bio:            "Gyanodaya Bal avam Mahila Kalyan Samiti (GBMKS)"
      email:          gyanoday.bmks@gmail.com

    kirtika:
      name:           Kirtika Sharma
      site:           https://www.wowthemes.net
      avatar:         assets/images/kirtika.jpg
      bio:            "Secretary-GBMKS-9140523092"
      email:          gyanoday.bmks@gmail.com

    rashmika:
      name:           Rashmika Tripathi
      site:           https://www.wowthemes.net
      avatar:         assets/images/monu.jpg
      bio:            "Treasurer"
      email:          gyanoday.bmks@gmail.com

    utkarsh:
      name:           Utkarsh Rai
      site:           https://www.wowthemes.net
      avatar:         assets/images/utkarsh_rai.jpg
      bio:            "Website management"
      email:          gyanoday.bmks@gmail.com
      linkedin:       https://www.linkedin.com/in/utkarsh-rai-b71878111/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: utkarsh
      avatar: assets/images/avatar.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]